document.addEventListener("DOMContentLoaded",()=>{let L=document.querySelectorAll(".product-card__button"),l=document.querySelector(".cart-content__list"),p=document.querySelector(".cart"),v=p.querySelector(".cart__quantity"),b=document.querySelector(".cart-content__fullprice"),m=document.querySelector(".order-modal__btn"),i=document.querySelector(".order-modal__list"),u=0,x=0,_=[],a=t=>t.replace(/\s/g,""),g=t=>String(t).replace(/(\d)(?=(\d\d\d)+([^\d]|$))/g,"$1 "),C=t=>u+=t,$=t=>u-=t,S=()=>{let t=l.querySelector(".simplebar-content").children.length;v.textContent=t,t>0?p.classList.add("active"):p.classList.remove("active")},y=()=>{b.textContent=`${g(u)} \u20BD`},M=(t,e,r,c)=>`
		<li class="cart-content__item">
			<article class="cart-content__product cart-product" data-id="${c}">
				<img src="${t}" alt="" class="cart-product__img">
				<div class="cart-product__text">
					<h3 class="cart-product__title">${e}</h3>
					<span class="cart-product__price">${g(r)}</span>
				</div>
				<button class="cart-product__delete" aria-label="\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0442\u043E\u0432\u0430\u0440"></button>
			</article>
		</li>
	`,E=t=>{let e=t.querySelector(".cart-product").dataset.id;document.querySelector(`.product-card[data-id="${e}"]`).querySelector(".product-card__button").disabled=!1;let r=parseInt(a(t.querySelector(".cart-product__price").textContent));$(r),y(),t.remove(),S(),h()},P=()=>{document.querySelectorAll(".cart-content__item").forEach(t=>{u+=parseInt(a(t.querySelector(".cart-product__price").textContent))})};(()=>{localStorage.getItem("products")!==null&&(console.log(localStorage.getItem("products")),l.querySelector(".simplebar-content").innerHTML=localStorage.getItem("products"),S(),P(),y(),document.querySelectorAll(".cart-content__product").forEach(t=>{let e=t.dataset.id;console.log(e)}))})();let h=()=>{let e=l.querySelector(".simplebar-content").innerHTML;e=e.trim(),console.log(e),console.log(e.length),e.length?localStorage.setItem("products",e):localStorage.removeItem("products")};L.forEach(t=>{t.closest(".product-card").setAttribute("data-id",x++),t.addEventListener("click",e=>{let r=e.currentTarget,c=r.closest(".product-card"),d=c.dataset.id,n=c.querySelector(".product-card__image").getAttribute("src"),o=c.querySelector(".product-card__subtitle").textContent,f=a(c.querySelector(".food__price").textContent),s=parseInt(a(c.querySelector(".food__price").textContent));C(s),y(),l.querySelector(".simplebar-content").insertAdjacentHTML("afterbegin",M(n,o,f,d)),S(),h(),r.disabled=!0})}),l.addEventListener("click",t=>{t.target.classList.contains("cart-product__delete")&&E(t.target.closest(".cart-content__item"))});let q=0;m.addEventListener("click",t=>{q==0?(m.classList.add("open"),i.style.display="block",q=1):(m.classList.remove("open"),i.style.display="none",q=0)});let A=(t,e,r,c)=>`
		<li class="order-modal__item">
			<article class="order-modal__product order-product" data-id="${c}">
				<img src="${t}" alt="" class="order-modal__img">
				<div class="order-product__text">
					<h3 class="order-product__title">${e}</h3>
					<span class="order-product__price">${g(r)}</span>
				</div>
			</article>
		</li>
	`,T=new GraphModal({isOpen:t=>{i.innerHTML="",console.log("opened");let e=l.querySelector(".simplebar-content").children,r=b.textContent,c=e.length;document.querySelector(".order-modal__quantity span").textContent=`${c} \u0448\u0442`,document.querySelector(".order-modal__summ span").textContent=`${r}`;for(item of e){console.log(item);let d=item.querySelector(".cart-product__img").getAttribute("src"),n=item.querySelector(".cart-product__title").textContent,o=a(item.querySelector(".cart-product__price").textContent),f=item.querySelector(".cart-product").dataset.id;i.insertAdjacentHTML("afterbegin",A(d,n,o,f));let s={};s.title=n,s.price=o,_.push(s)}console.log(_)},isClose:()=>{console.log("closed")}});document.querySelector(".order").addEventListener("submit",t=>{t.preventDefault();let e=t.currentTarget,r=new FormData(e),c=e.querySelector('[name="\u0418\u043C\u044F"]').value,d=e.querySelector('[name="\u0422\u0435\u043B\u0435\u0444\u043E\u043D"]').value,n=e.querySelector('[name="Email"]').value;r.append("\u0422\u043E\u0432\u0430\u0440\u044B",JSON.stringify(_)),r.append("\u0418\u043C\u044F",c),r.append("\u0422\u0435\u043B\u0435\u0444\u043E\u043D",d),r.append("Email",n);let o=new XMLHttpRequest;o.onreadystatechange=function(){o.readyState===4&&o.status===200&&console.log("\u041E\u0442\u043F\u0440\u0430\u0432\u043B\u0435\u043D\u043E")},o.open("POST","mail.php",!0),o.send(r),e.reset()})});
