document.addEventListener("DOMContentLoaded",()=>{let C=document.querySelectorAll(".product-card__button"),l=document.querySelector(".cart-content__list"),p=document.querySelector(".cart"),L=p.querySelector(".cart__quantity"),v=document.querySelector(".cart-content__fullprice"),_=document.querySelector(".order-modal__btn"),s=document.querySelector(".order-modal__list"),i=0,E=0,m=[],u=e=>e.replace(/\s/g,""),y=e=>String(e).replace(/(\d)(?=(\d\d\d)+([^\d]|$))/g,"$1 "),f=e=>i+=e,x=e=>i-=e,S=()=>{let e=l.querySelector(".simplebar-content").children.length;L.textContent=e,e>0?p.classList.add("active"):p.classList.remove("active")},g=()=>{v.textContent=`${y(i)} \u20BD`},$=(e,t,r,c)=>`
		<li class="cart-content__item">
			<article class="cart-content__product cart-product" data-id="${c}">
				<img src="${e}" alt="" class="cart-product__img">
				<div class="cart-product__text">
					<h3 class="cart-product__title">${t}</h3>
					<span class="cart-product__price">${y(r)}</span>
				</div>
				<button class="cart-product__delete" aria-label="\u0423\u0434\u0430\u043B\u0438\u0442\u044C \u0442\u043E\u0432\u0430\u0440"></button>
			</article>
		</li>
	`,A=e=>{let t=e.querySelector(".cart-product").dataset.id;document.querySelector(`.product-card[data-id="${t}"]`).querySelector(".product-card__button").disabled=!1;let r=parseInt(u(e.querySelector(".cart-product__price").textContent));x(r),g(),e.remove(),S(),h()},M=()=>{document.querySelectorAll(".cart-content__item").forEach(e=>{i+=parseInt(u(e.querySelector(".cart-product__price").textContent))})};localStorage.getItem("products")!==null&&(console.log(localStorage.getItem("products")),l.querySelector(".simplebar-content").innerHTML=localStorage.getItem("products"),S(),M(),g(),document.querySelectorAll(".cart-content__product").forEach(e=>{let t=e.dataset.id;console.log(t)}));let h=()=>{let e=l.querySelector(".simplebar-content").innerHTML;e=e.trim(),console.log(e),console.log(e.length),e.length?localStorage.setItem("products",e):localStorage.removeItem("products")};C.forEach(e=>{e.closest(".product-card").setAttribute("data-id",E++),e.addEventListener("click",t=>{let r=t.currentTarget,c=r.closest(".product-card"),n=c.dataset.id,a=c.querySelector(".product-card__image").getAttribute("src"),o=c.querySelector(".product-card__subtitle").textContent,b=u(c.querySelector(".food__price").textContent),d=parseInt(u(c.querySelector(".food__price").textContent));f(d),g(),l.querySelector(".simplebar-content").insertAdjacentHTML("afterbegin",$(a,o,b,n)),S(),h(),r.disabled=!0})}),l.addEventListener("click",e=>{e.target.classList.contains("cart-product__delete")&&A(e.target.closest(".cart-content__item"))});let q=0;_.addEventListener("click",e=>{q==0?(_.classList.add("open"),s.style.display="block",q=1):(_.classList.remove("open"),s.style.display="none",q=0)});let T=(e,t,r,c)=>`
		<li class="order-modal__item">
			<article class="order-modal__product order-product" data-id="${c}">
				<img src="${e}" alt="" class="order-modal__img">
				<div class="order-product__text">
					<h3 class="order-product__title">${t}</h3>
					<span class="order-product__price">${y(r)}</span>
				</div>
			</article>
		</li>
	`,I=new GraphModal({isOpen:e=>{s.innerHTML="",console.log("opened");let t=l.querySelector(".simplebar-content").children,r=v.textContent,c=t.length;document.querySelector(".order-modal__quantity span").textContent=`${c} \u0448\u0442`,document.querySelector(".order-modal__summ span").textContent=`${r}`;for(item of t){console.log(item);let n=item.querySelector(".cart-product__img").getAttribute("src"),a=item.querySelector(".cart-product__title").textContent,o=u(item.querySelector(".cart-product__price").textContent),b=item.querySelector(".cart-product").dataset.id;s.insertAdjacentHTML("afterbegin",T(n,a,o,b));let d={};d.title=a,d.price=o,m.push(d)}console.log(m)},isClose:()=>{console.log("closed")}});document.querySelector(".order").addEventListener("submit",e=>{e.preventDefault();let t=e.currentTarget,r=new FormData(t),c=t.querySelector('[name="\u0418\u043C\u044F"]').value,n=t.querySelector('[name="\u0422\u0435\u043B\u0435\u0444\u043E\u043D"]').value,a=t.querySelector('[name="Email"]').value;r.append("\u0422\u043E\u0432\u0430\u0440\u044B",JSON.stringify(m)),r.append("\u0418\u043C\u044F",c),r.append("\u0422\u0435\u043B\u0435\u0444\u043E\u043D",n),r.append("Email",a);let o=new XMLHttpRequest;o.onreadystatechange=function(){o.readyState===4&&o.status===200&&console.log("\u041E\u0442\u043F\u0440\u0430\u0432\u043B\u0435\u043D\u043E")},o.open("POST","mail.php",!0),o.send(r),t.reset()})});
